helper_node:
  ros__parameters:
    use_sim_time: false
    scan_topic: "/scan"
    cmd_topic: "/cmd_vel"
    rotation_service_name: "/rotate_to_yaw_degrees"
    linear_vel: 0.20
    odom_topic: "/odom"
    rotation_offset: 0.015 #radians
