behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
    # local_frame: odom
    global_frame: map
    robot_base_frame: robot_base_footprint
    transform_timeout: 0.1
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 2.0
    min_rotational_vel: 0.05
    rotational_acc_lim: 3.2
    time_allowance: 20.0
