behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]

    # Common parameters
    global_frame: odom
    robot_base_frame: robot_base_footprint
    transform_timeout: 0.5
    use_sim_time: True
    min_rotational_vel: 0.05
    max_rotational_vel: 1.5
    rotational_acc_lim: 3.2

    # Spin behavior
    spin:
      plugin: "nav2_behaviors/Spin"

    # BackUp behavior
    backup:
      plugin: "nav2_behaviors/BackUp"

    # Wait behavior
    wait:
      plugin: "nav2_behaviors/Wait"

