behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]

    # Common parameters
    global_frame: map
    robot_base_frame: robot_base_footprint
    transform_timeout: 0.1
    use_sim_time: True

    # Spin behavior
    spin:
      plugin: "nav2_behaviors/Spin"
      min_rotational_vel: 0.05
      max_rotational_vel: 1.5
      rotational_acc_lim: 3.2

    # BackUp behavior
    backup:
      plugin: "nav2_behaviors/BackUp"
      speed: -0.15
      min_x_velocity_threshold: 0.01

    # Wait behavior
    wait:
      plugin: "nav2_behaviors/Wait"
      wait_duration: 10.0

